import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Updated to match screenshot font
import { TRPCReactProvider } from "@/trpc/client"; // Imported as shown in image_87316a.jpg
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        {/* Wrapped children with TRPCReactProvider as shown in image_87316d.jpg */}
        <TRPCReactProvider>
          {children}
        </TRPCReactProvider>
      </body>
    </html>
  );
}